INSERT INTO champions (name, roles, tags)
VALUES
    ('Aatrox', ARRAY['top'], ARRAY[]::text[]),
    ('Ahri', ARRAY['mid'], ARRAY[]::text[]),
    ('Akali', ARRAY['mid', 'top'], ARRAY[]::text[]),
    ('Akshan', ARRAY['mid', 'adc'], ARRAY[]::text[]),
    ('Alistar', ARRAY['support'], ARRAY[]::text[]),
    ('Ambessa', ARRAY['top'], ARRAY[]::text[]),
    ('Amumu', ARRAY['jungle', 'support'], ARRAY[]::text[]),
    ('Anivia', ARRAY['mid'], ARRAY[]::text[]),
    ('Annie', ARRAY['mid', 'support'], ARRAY[]::text[]),
    ('Aphelios', ARRAY['adc'], ARRAY[]::text[]),
    ('Ashe', ARRAY['adc', 'support'], ARRAY[]::text[]),
    ('Aurelion Sol', ARRAY['mid'], ARRAY[]::text[]),
    ('Aurora', ARRAY['mid'], ARRAY[]::text[]),
    ('Azir', ARRAY['mid'], ARRAY[]::text[]),
    ('Bard', ARRAY['support'], ARRAY[]::text[]),
    ('Bel''Veth', ARRAY['jungle'], ARRAY[]::text[]),
    ('Blitzcrank', ARRAY['support'], ARRAY[]::text[]),
    ('Brand', ARRAY['support', 'mid'], ARRAY[]::text[]),
    ('Braum', ARRAY['support'], ARRAY[]::text[]),
    ('Briar', ARRAY['jungle'], ARRAY[]::text[]),
    ('Caitlyn', ARRAY['adc'], ARRAY[]::text[]),
    ('Camille', ARRAY['top'], ARRAY[]::text[]),
    ('Cassiopeia', ARRAY['mid'], ARRAY[]::text[]),
    ('Cho''Gath', ARRAY['top', 'mid'], ARRAY[]::text[]),
    ('Corki', ARRAY['mid'], ARRAY[]::text[]),
    ('Darius', ARRAY['top'], ARRAY[]::text[]),
    ('Diana', ARRAY['jungle', 'mid'], ARRAY[]::text[]),
    ('Draven', ARRAY['adc'], ARRAY[]::text[]),
    ('Dr. Mundo', ARRAY['top', 'jungle'], ARRAY[]::text[]),
    ('Ekko', ARRAY['mid', 'jungle'], ARRAY[]::text[]),
    ('Elise', ARRAY['jungle', 'support'], ARRAY[]::text[]),
    ('Evelynn', ARRAY['jungle'], ARRAY[]::text[]),
    ('Ezreal', ARRAY['adc'], ARRAY[]::text[]),
    ('Fiddlesticks', ARRAY['jungle', 'support'], ARRAY[]::text[]),
    ('Fiora', ARRAY['top'], ARRAY[]::text[]),
    ('Fizz', ARRAY['mid'], ARRAY[]::text[]),
    ('Galio', ARRAY['mid', 'support', 'top'], ARRAY[]::text[]),
    ('Gangplank', ARRAY['top'], ARRAY[]::text[]),
    ('Garen', ARRAY['top'], ARRAY[]::text[]),
    ('Gnar', ARRAY['top'], ARRAY[]::text[]),
    ('Gragas', ARRAY['jungle', 'top'], ARRAY[]::text[]),
    ('Graves', ARRAY['jungle'], ARRAY[]::text[]),
    ('Gwen', ARRAY['top'], ARRAY[]::text[]),
    ('Hecarim', ARRAY['jungle'], ARRAY[]::text[]),
    ('Heimerdinger', ARRAY['mid', 'support'], ARRAY[]::text[]),
    ('Hwei', ARRAY['mid'], ARRAY[]::text[]),
    ('Illaoi', ARRAY['top'], ARRAY[]::text[]),
    ('Irelia', ARRAY['top', 'mid'], ARRAY[]::text[]),
    ('Ivern', ARRAY['jungle'], ARRAY[]::text[]),
    ('Janna', ARRAY['support'], ARRAY[]::text[]),
    ('Jarvan IV', ARRAY['jungle'], ARRAY[]::text[]),
    ('Jax', ARRAY['top', 'jungle'], ARRAY[]::text[]),
    ('Jayce', ARRAY['top', 'mid'], ARRAY[]::text[]),
    ('Jhin', ARRAY['adc'], ARRAY[]::text[]),
    ('Jinx', ARRAY['adc'], ARRAY[]::text[]),
    ('K''Sante', ARRAY['top'], ARRAY[]::text[]),
    ('Kai''Sa', ARRAY['adc'], ARRAY[]::text[]),
    ('Kalista', ARRAY['adc'], ARRAY[]::text[]),
    ('Karma', ARRAY['support', 'mid'], ARRAY[]::text[]),
    ('Karthus', ARRAY['jungle'], ARRAY[]::text[]),
    ('Kassadin', ARRAY['mid'], ARRAY[]::text[]),
    ('Katarina', ARRAY['mid'], ARRAY[]::text[]),
    ('Kayle', ARRAY['top'], ARRAY[]::text[]),
    ('Kayn', ARRAY['jungle'], ARRAY[]::text[]),
    ('Kennen', ARRAY['top'], ARRAY[]::text[]),
    ('Kha''Zix', ARRAY['jungle'], ARRAY[]::text[]),
    ('Kindred', ARRAY['jungle'], ARRAY[]::text[]),
    ('Kled', ARRAY['top'], ARRAY[]::text[]),
    ('Kog''Maw', ARRAY['adc'], ARRAY[]::text[]),
    ('LeBlanc', ARRAY['mid'], ARRAY[]::text[]),
    ('Lee Sin', ARRAY['jungle'], ARRAY[]::text[]),
    ('Leona', ARRAY['support'], ARRAY[]::text[]),
    ('Lillia', ARRAY['jungle'], ARRAY[]::text[]),
    ('Lissandra', ARRAY['mid'], ARRAY[]::text[]),
    ('Lucian', ARRAY['adc'], ARRAY[]::text[]),
    ('Lulu', ARRAY['support', 'mid'], ARRAY[]::text[]),
    ('Lux', ARRAY['mid', 'support'], ARRAY[]::text[]),
    ('Malphite', ARRAY['top', 'mid'], ARRAY[]::text[]),
    ('Malzahar', ARRAY['mid'], ARRAY[]::text[]),
    ('Maokai', ARRAY['top', 'support'], ARRAY[]::text[]),
    ('Master Yi', ARRAY['jungle'], ARRAY[]::text[]),
    ('Miss Fortune', ARRAY['adc'], ARRAY[]::text[]),
    ('Mordekaiser', ARRAY['top'], ARRAY[]::text[]),
    ('Morgana', ARRAY['support', 'mid'], ARRAY[]::text[]),
    ('Nami', ARRAY['support'], ARRAY[]::text[]),
    ('Nasus', ARRAY['top'], ARRAY[]::text[]),
    ('Nautilus', ARRAY['support'], ARRAY[]::text[]),
    ('Neeko', ARRAY['mid', 'support'], ARRAY[]::text[]),
    ('Nidalee', ARRAY['jungle', 'mid'], ARRAY[]::text[]),
    ('Nilah', ARRAY['adc'], ARRAY[]::text[]),
    ('Nocturne', ARRAY['jungle'], ARRAY[]::text[]),
    ('Nunu & Willump', ARRAY['jungle'], ARRAY[]::text[]),
    ('Olaf', ARRAY['jungle', 'top'], ARRAY[]::text[]),
    ('Orianna', ARRAY['mid'], ARRAY[]::text[]),
    ('Ornn', ARRAY['top'], ARRAY[]::text[]),
    ('Pantheon', ARRAY['mid', 'support'], ARRAY[]::text[]),
    ('Poppy', ARRAY['top', 'support'], ARRAY[]::text[]),
    ('Pyke', ARRAY['support'], ARRAY[]::text[]),
    ('Qiyana', ARRAY['mid', 'jungle'], ARRAY[]::text[]),
    ('Quinn', ARRAY['top'], ARRAY[]::text[]),
    ('Rakan', ARRAY['support'], ARRAY[]::text[]),
    ('Rammus', ARRAY['jungle'], ARRAY[]::text[]),
    ('Rek''Sai', ARRAY['jungle'], ARRAY[]::text[]),
    ('Rell', ARRAY['support'], ARRAY[]::text[]),
    ('Renata Glasc', ARRAY['support'], ARRAY[]::text[]),
    ('Renekton', ARRAY['top'], ARRAY[]::text[]),
    ('Rengar', ARRAY['jungle', 'top'], ARRAY[]::text[]),
    ('Riven', ARRAY['top'], ARRAY[]::text[]),
    ('Rumble', ARRAY['top', 'mid'], ARRAY[]::text[]),
    ('Ryze', ARRAY['mid', 'top'], ARRAY[]::text[]),
    ('Samira', ARRAY['adc'], ARRAY[]::text[]),
    ('Sejuani', ARRAY['jungle'], ARRAY[]::text[]),
    ('Senna', ARRAY['adc', 'support'], ARRAY[]::text[]),
    ('Seraphine', ARRAY['mid', 'support'], ARRAY[]::text[]),
    ('Sett', ARRAY['top'], ARRAY[]::text[]),
    ('Shaco', ARRAY['jungle', 'support'], ARRAY[]::text[]),
    ('Shen', ARRAY['top'], ARRAY[]::text[]),
    ('Shyvana', ARRAY['jungle', 'top'], ARRAY[]::text[]),
    ('Singed', ARRAY['top'], ARRAY[]::text[]),
    ('Sion', ARRAY['top'], ARRAY[]::text[]),
    ('Sivir', ARRAY['adc'], ARRAY[]::text[]),
    ('Skarner', ARRAY['jungle'], ARRAY[]::text[]),
    ('Sona', ARRAY['support'], ARRAY[]::text[]),
    ('Soraka', ARRAY['support'], ARRAY[]::text[]),
    ('Swain', ARRAY['mid', 'support'], ARRAY[]::text[]),
    ('Sylas', ARRAY['mid', 'top'], ARRAY[]::text[]),
    ('Syndra', ARRAY['mid'], ARRAY[]::text[]),
    ('Tahm Kench', ARRAY['support', 'top'], ARRAY[]::text[]),
    ('Taliyah', ARRAY['jungle', 'mid'], ARRAY[]::text[]),
    ('Talon', ARRAY['mid'], ARRAY[]::text[]),
    ('Taric', ARRAY['support'], ARRAY[]::text[]),
    ('Teemo', ARRAY['top'], ARRAY[]::text[]),
    ('Thresh', ARRAY['support'], ARRAY[]::text[]),
    ('Tristana', ARRAY['adc', 'mid'], ARRAY[]::text[]),
    ('Trundle', ARRAY['jungle', 'top'], ARRAY[]::text[]),
    ('Tryndamere', ARRAY['top', 'mid'], ARRAY[]::text[]),
    ('Twisted Fate', ARRAY['mid'], ARRAY[]::text[]),
    ('Twitch', ARRAY['adc'], ARRAY[]::text[]),
    ('Udyr', ARRAY['jungle'], ARRAY[]::text[]),
    ('Urgot', ARRAY['top'], ARRAY[]::text[]),
    ('Varus', ARRAY['adc'], ARRAY[]::text[]),
    ('Vayne', ARRAY['adc', 'top'], ARRAY[]::text[]),
    ('Veigar', ARRAY['mid', 'adc'], ARRAY[]::text[]),
    ('Vel''Koz', ARRAY['support', 'mid'], ARRAY[]::text[]),
    ('Vex', ARRAY['mid'], ARRAY[]::text[]),
    ('Vi', ARRAY['jungle'], ARRAY[]::text[]),
    ('Viego', ARRAY['jungle'], ARRAY[]::text[]),
    ('Viktor', ARRAY['mid'], ARRAY[]::text[]),
    ('Vladimir', ARRAY['mid'], ARRAY[]::text[]),
    ('Volibear', ARRAY['top', 'jungle'], ARRAY[]::text[]),
    ('Warwick', ARRAY['jungle', 'top'], ARRAY[]::text[]),
    ('Xayah', ARRAY['adc'], ARRAY[]::text[]),
    ('Xerath', ARRAY['mid', 'support'], ARRAY[]::text[]),
    ('Xin Zhao', ARRAY['jungle'], ARRAY[]::text[]),
    ('Yasuo', ARRAY['mid', 'adc'], ARRAY[]::text[]),
    ('Yone', ARRAY['mid', 'top'], ARRAY[]::text[]),
    ('Yorick', ARRAY['top'], ARRAY[]::text[]),
    ('Yuumi', ARRAY['support'], ARRAY[]::text[]),
    ('Zac', ARRAY['jungle', 'support'], ARRAY[]::text[]),
    ('Zed', ARRAY['mid', 'jungle'], ARRAY[]::text[]),
    ('Zeri', ARRAY['adc'], ARRAY[]::text[]),
    ('Ziggs', ARRAY['adc', 'mid'], ARRAY[]::text[]),
    ('Zilean', ARRAY['support', 'mid'], ARRAY[]::text[]),
    ('Zoé', ARRAY['mid'], ARRAY[]::text[]),
    ('Zyra', ARRAY['support', 'mid'], ARRAY[]::text[]),
    ('Yunara', ARRAY['adc'], ARRAY[]::text[]),
    ('Zaahen', ARRAY['top', 'jungle'], ARRAY[]::text[]);
